const testWeatherData = {
  Copenhagen: {
    location: {
      name: "Athens",
      region: "Ohio",
      country: "United States of America",
      lat: 39.33,
      lon: -82.1,
      tz_id: "America/New_York",
      localtime_epoch: 1691726010,
      localtime: "2023-08-10 23:53",
    },
    current: {
      last_updated_epoch: 1691725500,
      last_updated: "2023-08-10 23:45",
      temp_c: 18.7,
      temp_f: 65.7,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 10,
      wind_dir: "N",
      pressure_mb: 1011,
      pressure_in: 29.86,
      precip_mm: 0,
      precip_in: 0,
      humidity: 93,
      cloud: 0,
      feelslike_c: 18.7,
      feelslike_f: 65.7,
      vis_km: 16,
      vis_miles: 9,
      uv: 1,
      gust_mph: 10.3,
      gust_kph: 16.6,
      air_quality: {
        co: 300.4,
        no2: 3,
        o3: 47.9,
        so2: 0.3,
        pm2_5: 8.2,
        pm10: 8.5,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-10",
          date_epoch: 1691625600,
          day: {
            maxtemp_c: 29.5,
            maxtemp_f: 85.1,
            mintemp_c: 19.5,
            mintemp_f: 67.1,
            avgtemp_c: 23.4,
            avgtemp_f: 74.1,
            maxwind_mph: 8.7,
            maxwind_kph: 14,
            totalprecip_mm: 17.6,
            totalprecip_in: 0.69,
            totalsnow_cm: 0,
            avgvis_km: 8.1,
            avgvis_miles: 5,
            avghumidity: 78,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 78,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:36 AM",
            sunset: "08:30 PM",
            moonrise: "01:11 AM",
            moonset: "04:48 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "34",
            is_moon_up: 0,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691643600,
              time: "2023-08-10 01:00",
              temp_c: 23.1,
              temp_f: 73.6,
              is_day: 0,
              condition: {
                text: "Thundery outbreaks possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/200.png",
                code: 1087,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 228,
              wind_dir: "SW",
              pressure_mb: 1008,
              pressure_in: 29.77,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 87,
              feelslike_c: 25.1,
              feelslike_f: 77.2,
              windchill_c: 23.1,
              windchill_f: 73.6,
              heatindex_c: 25.1,
              heatindex_f: 77.2,
              dewpoint_c: 18.3,
              dewpoint_f: 64.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  Venice: {},
  Vienna: {},
  London: {},
  Madrid: {},
  Paris: {},
  Zurich: {},
};

export { testWeatherData };
