const testWeatherData = [
  {
    location: {
      name: "Athens",
      region: "Ohio",
      country: "United States of America",
      lat: 39.33,
      lon: -82.1,
      tz_id: "America/New_York",
      localtime_epoch: 1691726010,
      localtime: "2023-08-10 23:53",
    },
    current: {
      last_updated_epoch: 1691725500,
      last_updated: "2023-08-10 23:45",
      temp_c: 18.7,
      temp_f: 65.7,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 10,
      wind_dir: "N",
      pressure_mb: 1011,
      pressure_in: 29.86,
      precip_mm: 0,
      precip_in: 0,
      humidity: 93,
      cloud: 0,
      feelslike_c: 18.7,
      feelslike_f: 65.7,
      vis_km: 16,
      vis_miles: 9,
      uv: 1,
      gust_mph: 10.3,
      gust_kph: 16.6,
      air_quality: {
        co: 300.4,
        no2: 3,
        o3: 47.9,
        so2: 0.3,
        pm2_5: 8.2,
        pm10: 8.5,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-10",
          date_epoch: 1691625600,
          day: {
            maxtemp_c: 29.5,
            maxtemp_f: 85.1,
            mintemp_c: 19.5,
            mintemp_f: 67.1,
            avgtemp_c: 23.4,
            avgtemp_f: 74.1,
            maxwind_mph: 8.7,
            maxwind_kph: 14,
            totalprecip_mm: 17.6,
            totalprecip_in: 0.69,
            totalsnow_cm: 0,
            avgvis_km: 8.1,
            avgvis_miles: 5,
            avghumidity: 78,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 78,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:36 AM",
            sunset: "08:30 PM",
            moonrise: "01:11 AM",
            moonset: "04:48 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "34",
            is_moon_up: 0,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691643600,
              time: "2023-08-10 01:00",
              temp_c: 23.1,
              temp_f: 73.6,
              is_day: 0,
              condition: {
                text: "Thundery outbreaks possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/200.png",
                code: 1087,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 228,
              wind_dir: "SW",
              pressure_mb: 1008,
              pressure_in: 29.77,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 87,
              feelslike_c: 25.1,
              feelslike_f: 77.2,
              windchill_c: 23.1,
              windchill_f: 73.6,
              heatindex_c: 25.1,
              heatindex_f: 77.2,
              dewpoint_c: 18.3,
              dewpoint_f: 64.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Copenhagen",
      region: "Hovedstaden",
      country: "Denmark",
      lat: 55.68,
      lon: 12.61,
      tz_id: "Europe/Copenhagen",
      localtime_epoch: 1691939325,
      localtime: "2023-08-13 17:08",
    },
    current: {
      last_updated_epoch: 1691938800,
      last_updated: "2023-08-13 17:00",
      temp_c: 22,
      temp_f: 71.6,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 12.5,
      wind_kph: 20.2,
      wind_degree: 230,
      wind_dir: "SW",
      pressure_mb: 1016,
      pressure_in: 30,
      precip_mm: 0,
      precip_in: 0,
      humidity: 65,
      cloud: 25,
      feelslike_c: 24.6,
      feelslike_f: 76.2,
      vis_km: 10,
      vis_miles: 6,
      uv: 6,
      gust_mph: 16.3,
      gust_kph: 26.3,
      air_quality: {
        co: 205.3,
        no2: 2.5,
        o3: 76.5,
        so2: 0.7,
        pm2_5: 3.2,
        pm10: 4.6,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 21,
            maxtemp_f: 69.8,
            mintemp_c: 15.5,
            mintemp_f: 59.9,
            avgtemp_c: 18.4,
            avgtemp_f: 65.1,
            maxwind_mph: 11.2,
            maxwind_kph: 18,
            totalprecip_mm: 1.4,
            totalprecip_in: 0.06,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 79,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 83,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 4,
          },
          astro: {
            sunrise: "05:38 AM",
            sunset: "08:51 PM",
            moonrise: "01:22 AM",
            moonset: "08:27 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 16.4,
              temp_f: 61.5,
              is_day: 0,
              condition: {
                text: "Light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
                code: 1183,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 269,
              wind_dir: "W",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 1,
              precip_in: 0.04,
              humidity: 96,
              cloud: 84,
              feelslike_c: 16.4,
              feelslike_f: 61.5,
              windchill_c: 16.4,
              windchill_f: 61.5,
              heatindex_c: 16.4,
              heatindex_f: 61.5,
              dewpoint_c: 15.8,
              dewpoint_f: 60.4,
              will_it_rain: 1,
              chance_of_rain: 83,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Zurich",
      region: "",
      country: "Switzerland",
      lat: 47.35,
      lon: 8.55,
      tz_id: "Europe/Zurich",
      localtime_epoch: 1691939942,
      localtime: "2023-08-13 17:19",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 17:15",
      temp_c: 30,
      temp_f: 86,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 266,
      wind_dir: "W",
      pressure_mb: 1017,
      pressure_in: 30.03,
      precip_mm: 0,
      precip_in: 0,
      humidity: 55,
      cloud: 0,
      feelslike_c: 31.1,
      feelslike_f: 88,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 0.9,
      gust_kph: 1.4,
      air_quality: {
        co: 210.3,
        no2: 8.9,
        o3: 79.4,
        so2: 1.9,
        pm2_5: 7.4,
        pm10: 8.9,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 29.8,
            maxtemp_f: 85.6,
            mintemp_c: 15.4,
            mintemp_f: 59.7,
            avgtemp_c: 22.3,
            avgtemp_f: 72.2,
            maxwind_mph: 2.9,
            maxwind_kph: 4.7,
            totalprecip_mm: 1.9,
            totalprecip_in: 0.07,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 73,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 84,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:19 AM",
            sunset: "08:41 PM",
            moonrise: "02:42 AM",
            moonset: "07:46 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 2,
              wind_kph: 3.2,
              wind_degree: 161,
              wind_dir: "SSE",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 92,
              cloud: 72,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 15.6,
              dewpoint_f: 60.1,
              will_it_rain: 1,
              chance_of_rain: 82,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.3,
              gust_kph: 6.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Mililani Town",
      region: "Hawaii",
      country: "United States of America",
      lat: 21.45,
      lon: -158.02,
      tz_id: "Pacific/Honolulu",
      localtime_epoch: 1691939971,
      localtime: "2023-08-13 5:19",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 05:15",
      temp_c: 19.2,
      temp_f: 66.6,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 10,
      wind_dir: "N",
      pressure_mb: 1019,
      pressure_in: 30.09,
      precip_mm: 0,
      precip_in: 0,
      humidity: 81,
      cloud: 0,
      feelslike_c: 19.2,
      feelslike_f: 66.6,
      vis_km: 16,
      vis_miles: 9,
      uv: 1,
      gust_mph: 12.5,
      gust_kph: 20.2,
      air_quality: {
        co: 136.9,
        no2: 0.2,
        o3: 46.5,
        so2: 0.2,
        pm2_5: 1.5,
        pm10: 6.1,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 27.9,
            maxtemp_f: 82.2,
            mintemp_c: 22.2,
            mintemp_f: 72,
            avgtemp_c: 24.4,
            avgtemp_f: 75.9,
            maxwind_mph: 13.2,
            maxwind_kph: 21.2,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 67,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:09 AM",
            sunset: "07:04 PM",
            moonrise: "03:48 AM",
            moonset: "05:44 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691924400,
              time: "2023-08-13 01:00",
              temp_c: 22.3,
              temp_f: 72.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 73,
              wind_dir: "ENE",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 23,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 22.4,
              windchill_f: 72.3,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 17.9,
              dewpoint_f: 64.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Copenhagen",
      region: "Hovedstaden",
      country: "Denmark",
      lat: 55.68,
      lon: 12.61,
      tz_id: "Europe/Copenhagen",
      localtime_epoch: 1691940597,
      localtime: "2023-08-13 17:29",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 17:15",
      temp_c: 22,
      temp_f: 71.6,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 12.5,
      wind_kph: 20.2,
      wind_degree: 230,
      wind_dir: "SW",
      pressure_mb: 1016,
      pressure_in: 30,
      precip_mm: 0,
      precip_in: 0,
      humidity: 65,
      cloud: 25,
      feelslike_c: 24.6,
      feelslike_f: 76.2,
      vis_km: 10,
      vis_miles: 6,
      uv: 6,
      gust_mph: 16.3,
      gust_kph: 26.3,
      air_quality: {
        co: 205.3,
        no2: 2.5,
        o3: 76.5,
        so2: 0.7,
        pm2_5: 3.2,
        pm10: 4.6,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 21,
            maxtemp_f: 69.8,
            mintemp_c: 15.5,
            mintemp_f: 59.9,
            avgtemp_c: 18.4,
            avgtemp_f: 65.1,
            maxwind_mph: 11.2,
            maxwind_kph: 18,
            totalprecip_mm: 1.4,
            totalprecip_in: 0.06,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 79,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 83,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 4,
          },
          astro: {
            sunrise: "05:38 AM",
            sunset: "08:51 PM",
            moonrise: "01:22 AM",
            moonset: "08:27 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 16.4,
              temp_f: 61.5,
              is_day: 0,
              condition: {
                text: "Light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
                code: 1183,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 269,
              wind_dir: "W",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 1,
              precip_in: 0.04,
              humidity: 96,
              cloud: 84,
              feelslike_c: 16.4,
              feelslike_f: 61.5,
              windchill_c: 16.4,
              windchill_f: 61.5,
              heatindex_c: 16.4,
              heatindex_f: 61.5,
              dewpoint_c: 15.8,
              dewpoint_f: 60.4,
              will_it_rain: 1,
              chance_of_rain: 83,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Ciputat",
      region: "West Java",
      country: "Indonesia",
      lat: -7.71,
      lon: 107.86,
      tz_id: "Asia/Jakarta",
      localtime_epoch: 1691940632,
      localtime: "2023-08-13 22:30",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 22:30",
      temp_c: 21.4,
      temp_f: 70.5,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 6.7,
      wind_kph: 10.8,
      wind_degree: 67,
      wind_dir: "ENE",
      pressure_mb: 1015,
      pressure_in: 29.96,
      precip_mm: 0,
      precip_in: 0,
      humidity: 87,
      cloud: 25,
      feelslike_c: 21.4,
      feelslike_f: 70.5,
      vis_km: 10,
      vis_miles: 6,
      uv: 1,
      gust_mph: 11.2,
      gust_kph: 18,
      air_quality: {
        co: 323.8,
        no2: 3.1,
        o3: 31.8,
        so2: 0.6,
        pm2_5: 9.1,
        pm10: 14.1,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 26.9,
            maxtemp_f: 80.4,
            mintemp_c: 20.2,
            mintemp_f: 68.4,
            avgtemp_c: 23,
            avgtemp_f: 73.4,
            maxwind_mph: 15.4,
            maxwind_kph: 24.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 74,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "05:58 AM",
            sunset: "05:49 PM",
            moonrise: "03:31 AM",
            moonset: "03:22 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691863200,
              time: "2023-08-13 01:00",
              temp_c: 21,
              temp_f: 69.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 74,
              wind_dir: "ENE",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 84,
              cloud: 0,
              feelslike_c: 21,
              feelslike_f: 69.8,
              windchill_c: 21,
              windchill_f: 69.8,
              heatindex_c: 21,
              heatindex_f: 69.8,
              dewpoint_c: 18.2,
              dewpoint_f: 64.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.4,
              gust_kph: 21.6,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Romanshorn",
      region: "",
      country: "Switzerland",
      lat: 47.57,
      lon: 9.36,
      tz_id: "Europe/Zurich",
      localtime_epoch: 1691940645,
      localtime: "2023-08-13 17:30",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 17:15",
      temp_c: 28,
      temp_f: 82.4,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 4.3,
      wind_kph: 6.8,
      wind_degree: 30,
      wind_dir: "NNE",
      pressure_mb: 1017,
      pressure_in: 30.03,
      precip_mm: 0,
      precip_in: 0,
      humidity: 51,
      cloud: 25,
      feelslike_c: 29.5,
      feelslike_f: 85.1,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 4.3,
      gust_kph: 6.8,
      air_quality: {
        co: 183.6,
        no2: 3.1,
        o3: 64.4,
        so2: 0.4,
        pm2_5: 5.4,
        pm10: 6.6,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 28.7,
            maxtemp_f: 83.7,
            mintemp_c: 15.4,
            mintemp_f: 59.7,
            avgtemp_c: 21.6,
            avgtemp_f: 70.8,
            maxwind_mph: 3.6,
            maxwind_kph: 5.8,
            totalprecip_mm: 0.2,
            totalprecip_in: 0.01,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 76,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 63,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:14 AM",
            sunset: "08:38 PM",
            moonrise: "02:36 AM",
            moonset: "07:44 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 16.4,
              temp_f: 61.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2,
              wind_kph: 3.2,
              wind_degree: 136,
              wind_dir: "SE",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 18,
              feelslike_c: 16.4,
              feelslike_f: 61.5,
              windchill_c: 16.4,
              windchill_f: 61.5,
              heatindex_c: 16.4,
              heatindex_f: 61.5,
              dewpoint_c: 15.1,
              dewpoint_f: 59.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.3,
              gust_kph: 6.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Vienna",
      region: "Wien",
      country: "Austria",
      lat: 48.19,
      lon: 16.31,
      tz_id: "Europe/Vienna",
      localtime_epoch: 1691940662,
      localtime: "2023-08-13 17:31",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 17:30",
      temp_c: 30,
      temp_f: 86,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 10.5,
      wind_kph: 16.9,
      wind_degree: 160,
      wind_dir: "SSE",
      pressure_mb: 1018,
      pressure_in: 30.06,
      precip_mm: 0,
      precip_in: 0,
      humidity: 49,
      cloud: 25,
      feelslike_c: 30.8,
      feelslike_f: 87.5,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 10.7,
      gust_kph: 17.3,
      air_quality: {
        co: 223.6,
        no2: 8,
        o3: 140.2,
        so2: 6.4,
        pm2_5: 13.7,
        pm10: 15.7,
        "us-epa-index": 1,
        "gb-defra-index": 2,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 31.1,
            maxtemp_f: 88,
            mintemp_c: 17.8,
            mintemp_f: 64,
            avgtemp_c: 24.3,
            avgtemp_f: 75.7,
            maxwind_mph: 8.5,
            maxwind_kph: 13.7,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 59,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "05:46 AM",
            sunset: "08:12 PM",
            moonrise: "02:05 AM",
            moonset: "07:19 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 18.8,
              temp_f: 65.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.5,
              wind_kph: 4,
              wind_degree: 164,
              wind_dir: "SSE",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 6,
              feelslike_c: 18.8,
              feelslike_f: 65.8,
              windchill_c: 18.8,
              windchill_f: 65.8,
              heatindex_c: 18.8,
              heatindex_f: 65.8,
              dewpoint_c: 14.3,
              dewpoint_f: 57.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Zurich",
      region: "",
      country: "Switzerland",
      lat: 47.35,
      lon: 8.55,
      tz_id: "Europe/Zurich",
      localtime_epoch: 1691940670,
      localtime: "2023-08-13 17:31",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 17:15",
      temp_c: 30,
      temp_f: 86,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 266,
      wind_dir: "W",
      pressure_mb: 1017,
      pressure_in: 30.03,
      precip_mm: 0,
      precip_in: 0,
      humidity: 55,
      cloud: 0,
      feelslike_c: 31.1,
      feelslike_f: 88,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 0.9,
      gust_kph: 1.4,
      air_quality: {
        co: 210.3,
        no2: 8.9,
        o3: 79.4,
        so2: 1.9,
        pm2_5: 7.4,
        pm10: 8.9,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 29.8,
            maxtemp_f: 85.6,
            mintemp_c: 15.4,
            mintemp_f: 59.7,
            avgtemp_c: 22.3,
            avgtemp_f: 72.2,
            maxwind_mph: 2.9,
            maxwind_kph: 4.7,
            totalprecip_mm: 1.9,
            totalprecip_in: 0.07,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 73,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 84,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:19 AM",
            sunset: "08:41 PM",
            moonrise: "02:42 AM",
            moonset: "07:46 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 2,
              wind_kph: 3.2,
              wind_degree: 161,
              wind_dir: "SSE",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 92,
              cloud: 72,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 15.6,
              dewpoint_f: 60.1,
              will_it_rain: 1,
              chance_of_rain: 82,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.3,
              gust_kph: 6.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Quilmes",
      region: "Buenos Aires",
      country: "Argentina",
      lat: -34.64,
      lon: -58.42,
      tz_id: "America/Argentina/Buenos_Aires",
      localtime_epoch: 1691940686,
      localtime: "2023-08-13 12:31",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 12:15",
      temp_c: 12,
      temp_f: 53.6,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 10.5,
      wind_kph: 16.9,
      wind_degree: 340,
      wind_dir: "NNW",
      pressure_mb: 1025,
      pressure_in: 30.27,
      precip_mm: 0,
      precip_in: 0,
      humidity: 41,
      cloud: 0,
      feelslike_c: 10.1,
      feelslike_f: 50.2,
      vis_km: 10,
      vis_miles: 6,
      uv: 4,
      gust_mph: 13.6,
      gust_kph: 22,
      air_quality: {
        co: 487.3,
        no2: 22.6,
        o3: 21.1,
        so2: 13.6,
        pm2_5: 9.8,
        pm10: 12.9,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 14.6,
            maxtemp_f: 58.3,
            mintemp_c: 6.8,
            mintemp_f: 44.2,
            avgtemp_c: 10.5,
            avgtemp_f: 50.9,
            maxwind_mph: 13,
            maxwind_kph: 20.9,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 42,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 4,
          },
          astro: {
            sunrise: "07:36 AM",
            sunset: "06:21 PM",
            moonrise: "06:09 AM",
            moonset: "03:43 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691899200,
              time: "2023-08-13 01:00",
              temp_c: 7.6,
              temp_f: 45.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 284,
              wind_dir: "WNW",
              pressure_mb: 1028,
              pressure_in: 30.34,
              precip_mm: 0,
              precip_in: 0,
              humidity: 41,
              cloud: 3,
              feelslike_c: 6.9,
              feelslike_f: 44.4,
              windchill_c: 6.9,
              windchill_f: 44.4,
              heatindex_c: 7.6,
              heatindex_f: 45.7,
              dewpoint_c: -4.8,
              dewpoint_f: 23.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Mililani Town",
      region: "Hawaii",
      country: "United States of America",
      lat: 21.45,
      lon: -158.02,
      tz_id: "Pacific/Honolulu",
      localtime_epoch: 1691940697,
      localtime: "2023-08-13 5:31",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 05:30",
      temp_c: 19.2,
      temp_f: 66.6,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 10,
      wind_dir: "N",
      pressure_mb: 1019,
      pressure_in: 30.09,
      precip_mm: 0,
      precip_in: 0,
      humidity: 81,
      cloud: 0,
      feelslike_c: 19.2,
      feelslike_f: 66.6,
      vis_km: 16,
      vis_miles: 9,
      uv: 1,
      gust_mph: 12.5,
      gust_kph: 20.2,
      air_quality: {
        co: 136.9,
        no2: 0.2,
        o3: 46.5,
        so2: 0.2,
        pm2_5: 1.5,
        pm10: 6.1,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 27.9,
            maxtemp_f: 82.2,
            mintemp_c: 22.2,
            mintemp_f: 72,
            avgtemp_c: 24.4,
            avgtemp_f: 75.9,
            maxwind_mph: 13.2,
            maxwind_kph: 21.2,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 67,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:09 AM",
            sunset: "07:04 PM",
            moonrise: "03:48 AM",
            moonset: "05:44 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691924400,
              time: "2023-08-13 01:00",
              temp_c: 22.3,
              temp_f: 72.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 73,
              wind_dir: "ENE",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 23,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 22.4,
              windchill_f: 72.3,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 17.9,
              dewpoint_f: 64.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Nairobi",
      region: "Nairobi Area",
      country: "Kenya",
      lat: -1.31,
      lon: 36.8,
      tz_id: "Africa/Nairobi",
      localtime_epoch: 1691940710,
      localtime: "2023-08-13 18:31",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 18:30",
      temp_c: 24,
      temp_f: 75.2,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 11.9,
      wind_kph: 19.1,
      wind_degree: 60,
      wind_dir: "ENE",
      pressure_mb: 1022,
      pressure_in: 30.18,
      precip_mm: 0,
      precip_in: 0,
      humidity: 36,
      cloud: 50,
      feelslike_c: 25.3,
      feelslike_f: 77.5,
      vis_km: 10,
      vis_miles: 6,
      uv: 6,
      gust_mph: 15.9,
      gust_kph: 25.6,
      air_quality: {
        co: 407.2,
        no2: 4.9,
        o3: 45.4,
        so2: 5,
        pm2_5: 8.4,
        pm10: 20.7,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 23.1,
            maxtemp_f: 73.6,
            mintemp_c: 13.9,
            mintemp_f: 57,
            avgtemp_c: 18,
            avgtemp_f: 64.4,
            maxwind_mph: 13.6,
            maxwind_kph: 22,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 64,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:35 AM",
            sunset: "06:40 PM",
            moonrise: "04:11 AM",
            moonset: "04:30 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691877600,
              time: "2023-08-13 01:00",
              temp_c: 15.7,
              temp_f: 60.3,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 74,
              wind_dir: "ENE",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 73,
              cloud: 43,
              feelslike_c: 15.7,
              feelslike_f: 60.3,
              windchill_c: 15.7,
              windchill_f: 60.3,
              heatindex_c: 15.7,
              heatindex_f: 60.3,
              dewpoint_c: 10.9,
              dewpoint_f: 51.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Fairbanks",
      region: "Alaska",
      country: "United States of America",
      lat: 64.84,
      lon: -147.7,
      tz_id: "America/Anchorage",
      localtime_epoch: 1691940723,
      localtime: "2023-08-13 7:32",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 07:30",
      temp_c: 12,
      temp_f: 53.6,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 2.2,
      wind_kph: 3.6,
      wind_degree: 10,
      wind_dir: "N",
      pressure_mb: 1000,
      pressure_in: 29.52,
      precip_mm: 0,
      precip_in: 0,
      humidity: 88,
      cloud: 75,
      feelslike_c: 12.3,
      feelslike_f: 54.2,
      vis_km: 16,
      vis_miles: 9,
      uv: 4,
      gust_mph: 4.5,
      gust_kph: 7.2,
      air_quality: {
        co: 201.9,
        no2: 3.9,
        o3: 20,
        so2: 0.4,
        pm2_5: 0.5,
        pm10: 0.6,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 21.7,
            maxtemp_f: 71.1,
            mintemp_c: 11.4,
            mintemp_f: 52.5,
            avgtemp_c: 16.1,
            avgtemp_f: 60.9,
            maxwind_mph: 10.5,
            maxwind_kph: 16.9,
            totalprecip_mm: 0.5,
            totalprecip_in: 0.02,
            totalsnow_cm: 0,
            avgvis_km: 9.6,
            avgvis_miles: 5,
            avghumidity: 61,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 86,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 4,
          },
          astro: {
            sunrise: "05:32 AM",
            sunset: "10:18 PM",
            moonrise: "12:00 AM",
            moonset: "12:00 AM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691917200,
              time: "2023-08-13 01:00",
              temp_c: 13.3,
              temp_f: 55.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 65,
              wind_dir: "ENE",
              pressure_mb: 996,
              pressure_in: 29.41,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 22,
              feelslike_c: 13,
              feelslike_f: 55.4,
              windchill_c: 13,
              windchill_f: 55.4,
              heatindex_c: 13.3,
              heatindex_f: 55.9,
              dewpoint_c: 8,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Nea Smyrni",
      region: "Attica",
      country: "Greece",
      lat: 37.97,
      lon: 23.73,
      tz_id: "Europe/Athens",
      localtime_epoch: 1691940726,
      localtime: "2023-08-13 18:32",
    },
    current: {
      last_updated_epoch: 1691939700,
      last_updated: "2023-08-13 18:15",
      temp_c: 26,
      temp_f: 78.8,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 20.6,
      wind_kph: 33.1,
      wind_degree: 360,
      wind_dir: "N",
      pressure_mb: 1013,
      pressure_in: 29.91,
      precip_mm: 0,
      precip_in: 0,
      humidity: 54,
      cloud: 75,
      feelslike_c: 26.9,
      feelslike_f: 80.3,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 16.3,
      gust_kph: 26.3,
      air_quality: {
        co: 201.9,
        no2: 1.7,
        o3: 93,
        so2: 2.3,
        pm2_5: 2.6,
        pm10: 3.1,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 27.4,
            maxtemp_f: 81.3,
            mintemp_c: 23.1,
            mintemp_f: 73.6,
            avgtemp_c: 25.5,
            avgtemp_f: 77.8,
            maxwind_mph: 21,
            maxwind_kph: 33.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 54,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            uv: 7,
          },
          astro: {
            sunrise: "06:38 AM",
            sunset: "08:21 PM",
            moonrise: "03:23 AM",
            moonset: "07:03 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691877600,
              time: "2023-08-13 01:00",
              temp_c: 24.5,
              temp_f: 76.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 2,
              wind_dir: "N",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 20,
              feelslike_c: 25.6,
              feelslike_f: 78.1,
              windchill_c: 24.5,
              windchill_f: 76.1,
              heatindex_c: 25.6,
              heatindex_f: 78.1,
              dewpoint_c: 14.7,
              dewpoint_f: 58.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.1,
              gust_kph: 29.2,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Tucson",
      region: "Arizona",
      country: "United States of America",
      lat: 32.25,
      lon: -110.96,
      tz_id: "America/Phoenix",
      localtime_epoch: 1691940738,
      localtime: "2023-08-13 8:32",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 08:30",
      temp_c: 26.4,
      temp_f: 79.5,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 5.6,
      wind_kph: 9,
      wind_degree: 150,
      wind_dir: "SSE",
      pressure_mb: 1017,
      pressure_in: 30.04,
      precip_mm: 0,
      precip_in: 0,
      humidity: 42,
      cloud: 0,
      feelslike_c: 27,
      feelslike_f: 80.7,
      vis_km: 16,
      vis_miles: 9,
      uv: 7,
      gust_mph: 4,
      gust_kph: 6.5,
      air_quality: {
        co: 270.4,
        no2: 10.4,
        o3: 23.3,
        so2: 1.1,
        pm2_5: 4.2,
        pm10: 11.3,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 40.8,
            maxtemp_f: 105.4,
            mintemp_c: 22.9,
            mintemp_f: 73.2,
            avgtemp_c: 31.8,
            avgtemp_f: 89.3,
            maxwind_mph: 17.2,
            maxwind_kph: 27.7,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 33,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 8,
          },
          astro: {
            sunrise: "05:47 AM",
            sunset: "07:10 PM",
            moonrise: "03:02 AM",
            moonset: "05:59 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 1,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691913600,
              time: "2023-08-13 01:00",
              temp_c: 28.2,
              temp_f: 82.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 141,
              wind_dir: "SE",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 28,
              feelslike_f: 82.4,
              windchill_c: 28.2,
              windchill_f: 82.8,
              heatindex_c: 28,
              heatindex_f: 82.4,
              dewpoint_c: 13.3,
              dewpoint_f: 55.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Calais",
      region: "Nord-Pas-de-Calais",
      country: "France",
      lat: 50.97,
      lon: 1.83,
      tz_id: "Europe/Paris",
      localtime_epoch: 1691940749,
      localtime: "2023-08-13 17:32",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 17:30",
      temp_c: 20,
      temp_f: 68,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 11.9,
      wind_kph: 19.1,
      wind_degree: 260,
      wind_dir: "W",
      pressure_mb: 1016,
      pressure_in: 30,
      precip_mm: 0,
      precip_in: 0,
      humidity: 78,
      cloud: 25,
      feelslike_c: 20,
      feelslike_f: 68,
      vis_km: 10,
      vis_miles: 6,
      uv: 5,
      gust_mph: 20.8,
      gust_kph: 33.5,
      air_quality: {
        co: 212,
        no2: 0.9,
        o3: 95.8,
        so2: 2,
        pm2_5: 9.9,
        pm10: 18.7,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 19,
            maxtemp_f: 66.2,
            mintemp_c: 16.3,
            mintemp_f: 61.3,
            avgtemp_c: 17.8,
            avgtemp_f: 64,
            maxwind_mph: 19.2,
            maxwind_kph: 31,
            totalprecip_mm: 0.5,
            totalprecip_in: 0.02,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 82,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 89,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 4,
          },
          astro: {
            sunrise: "06:36 AM",
            sunset: "09:18 PM",
            moonrise: "02:47 AM",
            moonset: "08:35 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 17.3,
              temp_f: 63.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 16.8,
              wind_kph: 27,
              wind_degree: 234,
              wind_dir: "SW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 10,
              feelslike_c: 17.3,
              feelslike_f: 63.1,
              windchill_c: 17.3,
              windchill_f: 63.1,
              heatindex_c: 17.3,
              heatindex_f: 63.1,
              dewpoint_c: 14.9,
              dewpoint_f: 58.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 24.6,
              gust_kph: 39.6,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Venezia",
      region: "Veneto",
      country: "Italy",
      lat: 45.44,
      lon: 12.33,
      tz_id: "Europe/Rome",
      localtime_epoch: 1691940760,
      localtime: "2023-08-13 17:32",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 17:30",
      temp_c: 30,
      temp_f: 86,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 4.3,
      wind_kph: 6.8,
      wind_degree: 170,
      wind_dir: "S",
      pressure_mb: 1017,
      pressure_in: 30.03,
      precip_mm: 0,
      precip_in: 0,
      humidity: 49,
      cloud: 0,
      feelslike_c: 33.8,
      feelslike_f: 92.8,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 6.9,
      gust_kph: 11.2,
      air_quality: {
        co: 293.7,
        no2: 14.9,
        o3: 154.5,
        so2: 5.3,
        pm2_5: 25.7,
        pm10: 28.4,
        "us-epa-index": 2,
        "gb-defra-index": 3,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 28,
            maxtemp_f: 82.4,
            mintemp_c: 20.5,
            mintemp_f: 68.9,
            avgtemp_c: 24.4,
            avgtemp_f: 76,
            maxwind_mph: 5.4,
            maxwind_kph: 8.6,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 72,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:08 AM",
            sunset: "08:22 PM",
            moonrise: "02:36 AM",
            moonset: "07:21 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 21.4,
              temp_f: 70.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 10,
              wind_dir: "N",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 7,
              feelslike_c: 21.4,
              feelslike_f: 70.5,
              windchill_c: 21.4,
              windchill_f: 70.5,
              heatindex_c: 24.4,
              heatindex_f: 75.9,
              dewpoint_c: 16.6,
              dewpoint_f: 61.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "London",
      region: "City of London, Greater London",
      country: "United Kingdom",
      lat: 51.5,
      lon: -0.14,
      tz_id: "Europe/London",
      localtime_epoch: 1691940770,
      localtime: "2023-08-13 16:32",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 16:30",
      temp_c: 19,
      temp_f: 66.2,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 11.9,
      wind_kph: 19.1,
      wind_degree: 220,
      wind_dir: "SW",
      pressure_mb: 1014,
      pressure_in: 29.94,
      precip_mm: 0,
      precip_in: 0,
      humidity: 60,
      cloud: 25,
      feelslike_c: 19,
      feelslike_f: 66.2,
      vis_km: 10,
      vis_miles: 6,
      uv: 6,
      gust_mph: 15,
      gust_kph: 24.1,
      air_quality: {
        co: 212,
        no2: 4.7,
        o3: 85.1,
        so2: 3.1,
        pm2_5: 3.2,
        pm10: 5.4,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 21.9,
            maxtemp_f: 71.4,
            mintemp_c: 15.5,
            mintemp_f: 59.9,
            avgtemp_c: 18,
            avgtemp_f: 64.5,
            maxwind_mph: 12.8,
            maxwind_kph: 20.5,
            totalprecip_mm: 1.2,
            totalprecip_in: 0.05,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 71,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 75,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 4,
          },
          astro: {
            sunrise: "05:43 AM",
            sunset: "08:27 PM",
            moonrise: "01:51 AM",
            moonset: "07:47 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691884800,
              time: "2023-08-13 01:00",
              temp_c: 15.7,
              temp_f: 60.3,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 226,
              wind_dir: "SW",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 52,
              feelslike_c: 15.7,
              feelslike_f: 60.3,
              windchill_c: 15.7,
              windchill_f: 60.3,
              heatindex_c: 15.7,
              heatindex_f: 60.3,
              dewpoint_c: 13.5,
              dewpoint_f: 56.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Madrid",
      region: "Madrid",
      country: "Spain",
      lat: 40.42,
      lon: -3.69,
      tz_id: "Europe/Madrid",
      localtime_epoch: 1691940781,
      localtime: "2023-08-13 17:33",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 17:30",
      temp_c: 36,
      temp_f: 96.8,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 8.1,
      wind_kph: 13,
      wind_degree: 220,
      wind_dir: "SW",
      pressure_mb: 1014,
      pressure_in: 29.94,
      precip_mm: 0,
      precip_in: 0,
      humidity: 25,
      cloud: 0,
      feelslike_c: 34.4,
      feelslike_f: 94,
      vis_km: 10,
      vis_miles: 6,
      uv: 9,
      gust_mph: 17.4,
      gust_kph: 28.1,
      air_quality: {
        co: 190.3,
        no2: 1.5,
        o3: 79.4,
        so2: 0.1,
        pm2_5: 1.7,
        pm10: 2,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 36.9,
            maxtemp_f: 98.4,
            mintemp_c: 24.1,
            mintemp_f: 75.4,
            avgtemp_c: 30.6,
            avgtemp_f: 87.1,
            maxwind_mph: 15.2,
            maxwind_kph: 24.5,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 27,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 8,
          },
          astro: {
            sunrise: "07:24 AM",
            sunset: "09:16 PM",
            moonrise: "04:07 AM",
            moonset: "08:05 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 28,
              temp_f: 82.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 1,
              wind_dir: "N",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 27,
              cloud: 3,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 28,
              windchill_f: 82.4,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 7.2,
              dewpoint_f: 45,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.5,
              gust_kph: 7.2,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "New York",
      region: "New York",
      country: "United States of America",
      lat: 40.74,
      lon: -73.99,
      tz_id: "America/New_York",
      localtime_epoch: 1691940795,
      localtime: "2023-08-13 11:33",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 11:30",
      temp_c: 25.6,
      temp_f: 78.1,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 6.9,
      wind_kph: 11.2,
      wind_degree: 270,
      wind_dir: "W",
      pressure_mb: 1012,
      pressure_in: 29.89,
      precip_mm: 0,
      precip_in: 0,
      humidity: 76,
      cloud: 50,
      feelslike_c: 28.1,
      feelslike_f: 82.5,
      vis_km: 16,
      vis_miles: 9,
      uv: 5,
      gust_mph: 8.7,
      gust_kph: 14,
      air_quality: {
        co: 357.2,
        no2: 9.2,
        o3: 114.4,
        so2: 4.4,
        pm2_5: 21,
        pm10: 23.9,
        "us-epa-index": 2,
        "gb-defra-index": 2,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 32.9,
            maxtemp_f: 91.2,
            mintemp_c: 21.1,
            mintemp_f: 70,
            avgtemp_c: 26.2,
            avgtemp_f: 79.2,
            maxwind_mph: 14.5,
            maxwind_kph: 23.4,
            totalprecip_mm: 11.1,
            totalprecip_in: 0.44,
            totalsnow_cm: 0,
            avgvis_km: 9.8,
            avgvis_miles: 6,
            avghumidity: 75,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 67,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:04 AM",
            sunset: "07:57 PM",
            moonrise: "02:58 AM",
            moonset: "06:55 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691902800,
              time: "2023-08-13 01:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 0,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                code: 1030,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 18,
              wind_dir: "NNE",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              humidity: 95,
              cloud: 100,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 22.5,
              dewpoint_f: 72.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Tamadjert",
      region: "Illizi",
      country: "Algeria",
      lat: 25.62,
      lon: 7.32,
      tz_id: "Africa/Algiers",
      localtime_epoch: 1691940823,
      localtime: "2023-08-13 16:33",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 16:30",
      temp_c: 35.7,
      temp_f: 96.3,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 8.7,
      wind_kph: 14,
      wind_degree: 53,
      wind_dir: "NE",
      pressure_mb: 1009,
      pressure_in: 29.8,
      precip_mm: 0,
      precip_in: 0,
      humidity: 11,
      cloud: 0,
      feelslike_c: 34.1,
      feelslike_f: 93.4,
      vis_km: 10,
      vis_miles: 6,
      uv: 9,
      gust_mph: 10.1,
      gust_kph: 16.2,
      air_quality: {
        co: 151.9,
        no2: 0.1,
        o3: 88,
        so2: 0.3,
        pm2_5: 14.8,
        pm10: 67.9,
        "us-epa-index": 1,
        "gb-defra-index": 2,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 35.7,
            maxtemp_f: 96.3,
            mintemp_c: 23.3,
            mintemp_f: 73.9,
            avgtemp_c: 30,
            avgtemp_f: 85.9,
            maxwind_mph: 13.4,
            maxwind_kph: 21.6,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 16,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 7,
          },
          astro: {
            sunrise: "06:04 AM",
            sunset: "07:06 PM",
            moonrise: "03:14 AM",
            moonset: "05:29 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691884800,
              time: "2023-08-13 01:00",
              temp_c: 27,
              temp_f: 80.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 98,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              humidity: 18,
              cloud: 0,
              feelslike_c: 25.2,
              feelslike_f: 77.4,
              windchill_c: 27,
              windchill_f: 80.6,
              heatindex_c: 25.2,
              heatindex_f: 77.4,
              dewpoint_c: 0.6,
              dewpoint_f: 33.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.1,
              gust_kph: 32.4,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Port Melbourne",
      region: "Victoria",
      country: "Australia",
      lat: -37.82,
      lon: 144.94,
      tz_id: "Australia/Melbourne",
      localtime_epoch: 1691940904,
      localtime: "2023-08-14 1:35",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-14 01:30",
      temp_c: 5,
      temp_f: 41,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 4.3,
      wind_kph: 6.8,
      wind_degree: 270,
      wind_dir: "W",
      pressure_mb: 1019,
      pressure_in: 30.09,
      precip_mm: 0,
      precip_in: 0,
      humidity: 93,
      cloud: 0,
      feelslike_c: 4.5,
      feelslike_f: 40.2,
      vis_km: 10,
      vis_miles: 6,
      uv: 1,
      gust_mph: 4.3,
      gust_kph: 6.8,
      air_quality: {
        co: 297.1,
        no2: 30.5,
        o3: 15,
        so2: 7.9,
        pm2_5: 4.5,
        pm10: 7.1,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-14",
          date_epoch: 1691971200,
          day: {
            maxtemp_c: 11.2,
            maxtemp_f: 52.2,
            mintemp_c: 5.4,
            mintemp_f: 41.7,
            avgtemp_c: 8.2,
            avgtemp_f: 46.8,
            maxwind_mph: 7.2,
            maxwind_kph: 11.5,
            totalprecip_mm: 0.1,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 68,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            uv: 3,
          },
          astro: {
            sunrise: "07:07 AM",
            sunset: "05:44 PM",
            moonrise: "06:06 AM",
            moonset: "03:25 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "5",
            is_moon_up: 1,
            is_sun_up: 1,
          },
          hour: [
            {
              time_epoch: 1691938800,
              time: "2023-08-14 01:00",
              temp_c: 7.1,
              temp_f: 44.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.5,
              wind_kph: 4,
              wind_degree: 139,
              wind_dir: "SE",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 6,
              feelslike_c: 6.8,
              feelslike_f: 44.2,
              windchill_c: 6.8,
              windchill_f: 44.2,
              heatindex_c: 7.1,
              heatindex_f: 44.8,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.3,
              gust_kph: 6.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  {
    location: {
      name: "Paris",
      region: "Ile-de-France",
      country: "France",
      lat: 48.86,
      lon: 2.35,
      tz_id: "Europe/Paris",
      localtime_epoch: 1691940939,
      localtime: "2023-08-13 17:35",
    },
    current: {
      last_updated_epoch: 1691940600,
      last_updated: "2023-08-13 17:30",
      temp_c: 23,
      temp_f: 73.4,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 11.9,
      wind_kph: 19.1,
      wind_degree: 240,
      wind_dir: "WSW",
      pressure_mb: 1017,
      pressure_in: 30.03,
      precip_mm: 0,
      precip_in: 0,
      humidity: 47,
      cloud: 0,
      feelslike_c: 24.4,
      feelslike_f: 75.9,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      gust_mph: 10.5,
      gust_kph: 16.9,
      air_quality: {
        co: 220.3,
        no2: 5.7,
        o3: 66.5,
        so2: 1,
        pm2_5: 2.3,
        pm10: 3.4,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-08-13",
          date_epoch: 1691884800,
          day: {
            maxtemp_c: 25.7,
            maxtemp_f: 78.3,
            mintemp_c: 16.6,
            mintemp_f: 61.9,
            avgtemp_c: 20.7,
            avgtemp_f: 69.3,
            maxwind_mph: 9.2,
            maxwind_kph: 14.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 57,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:40 AM",
            sunset: "09:10 PM",
            moonrise: "02:59 AM",
            moonset: "08:20 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1691881200,
              time: "2023-08-13 01:00",
              temp_c: 18.4,
              temp_f: 65.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 237,
              wind_dir: "WSW",
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 13,
              feelslike_c: 18.4,
              feelslike_f: 65.1,
              windchill_c: 18.4,
              windchill_f: 65.1,
              heatindex_c: 18.4,
              heatindex_f: 65.1,
              dewpoint_c: 11.1,
              dewpoint_f: 52,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
];

export { testWeatherData };
